### ISSUE TITLE
Wiring and alarm panel ports

### ISSUE THREAD

**Issue by nrwiersma** [HomeACcessoryKid/NX-8-alarm#1]
Hi, Thanks for a great project!

I have been looking for a way to read the state of my NetworX NX-8 into Home Assistant and stumbled onto your project. Looks like a great starting point for me.

Could you possibly explain how you wired the NX-8 to the ESP8266?

**Comment by HomeACcessoryKid** [comment]
Hi @nrwiersma,

For the avoidance of doubt, I assume you have read the following text from nx8bus.h, right?

```
 * This is a driver for the NX8 bus based on a 4512 bus driver with a fixed address selected and that pin gets 0 V input
 * The inhibit pin 15 is connected to a NPN driver with 10k collector to 12V bus power and by a base 180kohm to the tx pin 
 * The Zoutput pin 14 is connected to the bus dataline. So tx=0 is high-Z and tx=1 is zero out. The bus itself is 12v idle
 * The rx pin is reading the bus by a divider of 10k to ground and 33k to the dataline
```

The databus if an NX8 is a three wire bus that goes to all the control panels.
There is a ground and a 12V power and a dateline.
If you open the box where the NX8 board is inside, there are many screw terminals and these are roughly above the middle. They are labeled DATA, COM KEYPAD (=ground) and POS.
Just add three more wires and lead them to your setup with the 4512

Please start by reading the datasheet of 4512 chip if that is not clear enough for you.
Effectively, the databus is held high by a resistor to 12V by the nx8, and every control panel can pull it to ground to transmit a zero symbol. I kind of cheat by using the 4512 like this, but I had it in stock so that is what it was.
Any other chip from the 45xx series can be abused in a similar way if it has a high-Z and zero output you can control.

An NPN driver is a transistor like 2N3904 or BC547 or almost whatever...

The Rx and Tx pin are GPIO 5 and 4 as defined in main.c

There is an efficient way to tap the power for the ESP8266 from the 12V bus, but it requires getting more hardware gadgets. I used a buck-converter to step down from 12V to about 4.5V and then used a LDO to regulate down to 3V3.
The buck converter alone was not stable enough to deliver 3V3 and messed up the ESP8266.

I'll leave it at this for now,
Continue with more focused questions if needed.
Good luck

**Comment by HomeACcessoryKid** [comment]
A picture might help also.
Note that black and brown are combined to create a stronger ground.
![NX8-to-ESP8266](https://github.com/HomeACcessoryKid/NX-8-alarm/blob/master/NX8-to-ESP8266.png)

**Comment by nrwiersma** [comment]
Thanks for getting back to me so quickly. This unfortunately is entirely over my head, I am not that proficient in electronics. But this gives me a great starting point to start reading around the topic.

Thanks a bunch, appreciate it.
